feat: honor JBANG_DOWNLOAD_VERSION in bootstrap setup (#1505)
* feat: honor JBANG_DOWNLOAD_VERSION in bootstrap setup

* fix: fixed ENV variable handling

Co-authored-by: Tako Schotanus <tako@codejive.org>

diff --git a/src/main/scripts/jbang b/src/main/scripts/jbang
--- a/src/main/scripts/jbang
+++ b/src/main/scripts/jbang
@@ -144,11 +144,15 @@ elif [ -f "$abs_jbang_dir/.jbang/jbang.jar" ]; then
   jarPath=$abs_jbang_dir/.jbang/jbang.jar
 else
   if [[ ! -f "$JBDIR/bin/jbang.jar" || ! -f "$JBDIR/bin/jbang" ]]; then
-    echo "Downloading JBang..." 1>&2
+    echo "Downloading JBang $JBANG_DOWNLOAD_VERSION..." 1>&2
     mkdir -p "$TDIR/urls"
-    jburl="https://github.com/jbangdev/jbang/releases/latest/download/jbang.tar"
+    if [ -z "$JBANG_DOWNLOAD_VERSION" ]; then
+      jburl="https://github.com/jbangdev/jbang/releases/latest/download/jbang.tar";
+    else
+      jburl="https://github.com/jbangdev/jbang/releases/download/v$JBANG_DOWNLOAD_VERSION/jbang.tar";
+    fi
     download $jburl "$TDIR/urls/jbang.tar"
-    if [ $retval -ne 0 ]; then echo "Error downloading JBang" 1>&2; exit $retval; fi
+    if [ $retval -ne 0 ]; then echo "Error downloading JBang from $jburl" 1>&2; exit $retval; fi
     echo "Installing JBang..." 1>&2
     rm -rf "$TDIR/urls/jbang"
     tar xf "$TDIR/urls/jbang.tar" -C "$TDIR/urls"
