fix: do not fail on unrecognized OS like arm64 for new macs. should at least try run located java. (#657)
Co-authored-by: Max Rydahl Andersen <max@xam.dk>

diff --git a/src/main/scripts/jbang b/src/main/scripts/jbang
--- a/src/main/scripts/jbang
+++ b/src/main/scripts/jbang
@@ -48,7 +48,8 @@ case "$(uname -s)" in
     os=mac;;
   CYGWIN*|MINGW*|MSYS*)
     os=windows;;
-  *)        echo "Unsupported Operating System: $(uname -s)" 1>&2; exit 1;;
+  *)
+    os=
 esac
 
 case "$(uname -m)" in
@@ -61,7 +62,7 @@ case "$(uname -m)" in
   armv7l)
     arch=arm;;
   *)
-    echo "Unsupported Architecture: $(uname -m)" 1>&2; exit 1;;
+    arch=
 esac
 
 ## when mingw/git bash or cygwin fall out to just running the bat file.
@@ -119,6 +120,14 @@ if [[ -z "$JAVA_EXEC" ]]; then
     # Check if we installed a JDK before
     if [ ! -d "$TDIR/jdks/$javaVersion" ]; then
       # If not, download and install it
+      if [[ $os == "" ]]; then
+        echo "Unable to download JDK, unsupported Operating System: $(uname -s)" 1>&2
+        exit 1
+      fi
+      if [[ $arch == "" ]]; then
+        echo "Unable to download JDK, unsupported Architecture: $(uname -m)" 1>&2
+        exit 1
+      fi
       mkdir -p "$TDIR/jdks"
       echo "Downloading JDK $javaVersion. Be patient, this can take several minutes..." 1>&2
       jdkurl="https://api.adoptopenjdk.net/v3/binary/latest/$javaVersion/ga/$os/$arch/jdk/hotspot/normal/adoptopenjdk"
