Fixes #288 Add command to create "wrapper"
This version does not implement the option to skip copying the JAR file,
for that we need zero-install to be implemented first.

diff --git a/src/main/scripts/jbang b/src/main/scripts/jbang
--- a/src/main/scripts/jbang
+++ b/src/main/scripts/jbang
@@ -52,7 +52,14 @@ if [[ $os == windows ]]; then
 fi
 
 ## resolve application jar path from script location
-jarPath=$(dirname $abs_jbang_path)/jbang.jar
+if [ -f "$(dirname $abs_jbang_path)/jbang.jar" ]; then
+  jarPath=$(dirname $abs_jbang_path)/jbang.jar
+elif [ -f "$(dirname $abs_jbang_path)/.jbang/jbang.jar" ]; then
+  jarPath=$(dirname $abs_jbang_path)/.jbang/jbang.jar
+else
+  echo "Error: could not find jbang.jar file" 1>&2
+  exit 1
+fi
 
 if [[ -z "$JBANG_DIR" ]]; then JBDIR="$HOME/.jbang"; else JBDIR="$JBANG_DIR"; fi
 if [[ -z "$JBANG_CACHE_DIR" ]]; then TDIR="$JBDIR/cache"; else TDIR="$JBANG_CACHE_DIR"; fi
