Some better error checking for the bootstrap scripts

diff --git a/src/main/scripts/jbang b/src/main/scripts/jbang
--- a/src/main/scripts/jbang
+++ b/src/main/scripts/jbang
@@ -39,6 +39,8 @@ case "$(uname -p)" in
   *)        arch=x32;;
 esac
 
+url="https://api.adoptopenjdk.net/v3/binary/latest/$javaVersion/ga/$os/$arch/jdk/hotspot/normal/adoptopenjdk"
+
 abs_jbang_path=$(resolve_symlink $(absolute_path $0))
 
 ## when mingw/git bash or cygwin fall out to just running the bat file.
@@ -55,29 +57,44 @@ if [[ -z "$JBANG_CACHE_DIR" ]]; then TDIR="$JBDIR/cache"; else TDIR="$JBANG_CACH
 
 mkdir -p "$TDIR/jdks"
 
-## prefer JAVA instead of PATH to resolve `java` location
+# Find/get a JDK
 if [[ -z "$JAVA_HOME" ]]; then
-  if [ -x "$(command -v javac)" ]; then
+  # Determine if a (working) JDK is available on the PATH
+  javac -version > /dev/null 2>&1
+  if [ $? -eq 0 ]; then
     JAVA_EXEC="java";
   else
+    # Check if we installed a JDK before
     if [ ! -d "$TDIR/jdks/$javaVersion" ]; then
+      # If not, download and install it
       echo "Downloading JDK $javaVersion..."
-      url="https://api.adoptopenjdk.net/v3/binary/latest/$javaVersion/ga/$os/$arch/jdk/hotspot/normal/adoptopenjdk"
       if [ -x "$(command -v curl)" ]; then
         curl -sL -o "$TDIR/bootstrap-jdk.tgz" $url
+        retval=$?
       elif [ -x "$(command -v wget)" ]; then
         wget -q -O "$TDIR/bootstrap-jdk.tgz" $url
+        retval=$?
       else
         echo "Error: curl or wget not found, cannot download JDK"
         exit 1
       fi
+      if [ $retval -ne 0 ]; then echo "Error downloading JDK"; exit $retval; fi
       echo "Installing JDK $javaVersion..."
       rm -rf "$TDIR/jdks/$javaVersion.tmp/"
       mkdir -p "$TDIR/jdks/$javaVersion.tmp"
       tar xf "$TDIR/bootstrap-jdk.tgz" -C "$TDIR/jdks/$javaVersion.tmp" --strip-components=1
-      if [[ $os == mac ]]; then
+      retval=$?
+      if [[ $os == mac && $retval -eq 0 ]]; then
         mv "$TDIR/jdks/$javaVersion.tmp/Contents/Home/*" "$TDIR/jdks/$javaVersion.tmp/"
+        retval=$?
       fi
+      if [ $retval -ne 0 ]; then
+        # Check if the JDK was installed properly
+        javac -version > /dev/null 2>&1
+        retval=$?
+      fi
+      if [ $retval -ne 0 ]; then echo "Error installing JDK"; exit $retval; fi
+      # Activate the downloaded JDK giving it its proper name
       mv "$TDIR/jdks/$javaVersion.tmp" "$TDIR/jdks/$javaVersion"
     fi
     JAVA_HOME="$TDIR/jdks/$javaVersion"
